# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      scraping-url:
        # Description to be shown in the UI, instead of 'scraping-url'
        description: 'Scraping URL'
        # Default value if no value is explicitly provided
        default: 'gist.github.com/Iron-Wolf.html'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: context values
        run: |
          echo "URL : ${{ inputs.scraping-url }}";
      - name: Download website
        run: |
          wget \
            --recursive \
            --level=2 \
            --wait=1 \
            --no-clobber \
            --page-requisites \
            --html-extension \
            --convert-links \
            --domains quotes.toscrape.com \
            https://${{ inputs.scraping-url }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Scrapped result
          title: ${{ inputs.scraping-url }}
          body: Visualize here > https://raw.githack.com/Iron-Wolf/proxy-pass/scrape/${{ inputs.scraping-url }}
          branch: scrape
