# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      scraping_url:
        # Description to be shown in the UI, instead of 'scraping-url'
        description: 'Scraping URL'
        # Default value if no value is explicitly provided
        default: 'https://gist.github.com/Iron-Wolf'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      branch_name:
        default: 'scrape'
        required: true
        type: string

# doc : https://docs.github.com/en/actions/learn-github-actions/variables
env:
  base_url: ''

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      regex_base_url: '(?<=https://).*\.(\w){2,3}(?=/)'
      regex_no_http: '(?<=https://).*'
    steps:
      - uses: actions/checkout@v4
      - name: context values
        run: |
          echo "URL : ${{inputs.scraping_url}}"
          # use grep, because bash regex does not support lookahead (?)
          base_url=$(echo ${{inputs.scraping_url}} | grep -oP $regex_base_url)
          echo "base_url=$base_url" >> $GITHUB_ENV
          full_url_no_http=$(echo ${{inputs.scraping_url}} | grep -oP $regex_no_http)
          echo "full_url_no_http=$full_url_no_http" >> $GITHUB_ENV
      - name: Download website
        run: |
          wget \
            --recursive \
            --level=2 \
            --wait=1 \
            --no-clobber \
            --page-requisites \
            --html-extension \
            --convert-links \
            --domains quotes.toscrape.com \
            ${{ inputs.scraping_url }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Scrapped result
          title: "URL : ${{env.base_url}}"
          # action generate ".html" files
          body: Visualize here > https://raw.githack.com/Iron-Wolf/proxy-pass/${{inputs.branch_name}}/${{env.full_url_no_http}}.html
          branch: ${{inputs.branch_name}}
